language: python
python:
 - "2.7"
 - "3.4"
env:
  global:
   - DRF="djangorestframework==2.4.2"
  matrix:
   - DJANGO="django==1.6.7"
   - DJANGO="django==1.7"
install:
 - pip install $DJANGO
 - pip install $DRF
script:
 - python setup.py test
